//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

DATA LCDATA1<>+0x000(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCDATA1<>+0x008(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCDATA1<>+0x010(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCDATA1<>+0x018(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCDATA1<>+0x020(SB)/8, $0x0302020102010100
DATA LCDATA1<>+0x028(SB)/8, $0x0403030203020201
DATA LCDATA1<>+0x030(SB)/8, $0x0302020102010100
DATA LCDATA1<>+0x038(SB)/8, $0x0403030203020201
GLOBL LCDATA1<>(SB), 8, $64

TEXT ·_count_optimized(SB), $0-24

	MOVQ data+0(FP), DI
	MOVQ len+8(FP), SI
	MOVQ result+16(FP), DX
	LEAQ LCDATA1<>(SB), BP

	LONG $0x0002c748; WORD $0x0000; BYTE $0x00 // mov    qword [rdx], 0
	WORD $0x8948; BYTE $0xf1                   // mov    rcx, rsi
	LONG $0x20e9c148                           // shr    rcx, 32
	WORD $0x3145; BYTE $0xc0                   // xor    r8d, r8d
	LONG $0x0000ba41; WORD $0x0000             // mov    r10d, 0
	WORD $0xf983; BYTE $0x01                   // cmp    ecx, 1
	JNE  LBB0_7
	WORD $0xfe83; BYTE $0x40                   // cmp    esi, 64
	JB   LBB0_7
	WORD $0xf089                               // mov    eax, esi
	WORD $0xe8c1; BYTE $0x02                   // shr    eax, 2
	LONG $0xc0eff9c5                           // vpxor    xmm0, xmm0, xmm0
	LONG $0xc9eff1c5                           // vpxor    xmm1, xmm1, xmm1
	LONG $0xf6efc9c5                           // vpxor    xmm6, xmm6, xmm6
	LONG $0xef3941c4; BYTE $0xc0               // vpxor    xmm8, xmm8, xmm8
	LONG $0xffefc1c5                           // vpxor    xmm7, xmm7, xmm7
	LONG $0xd2efe9c5                           // vpxor    xmm2, xmm2, xmm2
	LONG $0xfffff025; BYTE $0x3f               // and    eax, 1073741808
	JE   LBB0_6
	WORD $0x8941; BYTE $0xc0                   // mov    r8d, eax
	LONG $0xe08f8d48; WORD $0x0001; BYTE $0x00 // lea    rcx, [rdi + 480]
	LONG $0xd2efe9c5                           // vpxor    xmm2, xmm2, xmm2
	WORD $0xc031                               // xor    eax, eax
	LONG $0x5d6ffdc5; BYTE $0x00               // vmovdqa    ymm3, yword 0[rbp] /* [rip + LCPI0_0] */
	LONG $0x656ffdc5; BYTE $0x20               // vmovdqa    ymm4, yword 32[rbp] /* [rip + LCPI0_1] */
	LONG $0xedefd1c5                           // vpxor    xmm5, xmm5, xmm5
	LONG $0xffefc1c5                           // vpxor    xmm7, xmm7, xmm7
	LONG $0xef3941c4; BYTE $0xc0               // vpxor    xmm8, xmm8, xmm8
	LONG $0xf6efc9c5                           // vpxor    xmm6, xmm6, xmm6
	LONG $0xc9eff1c5                           // vpxor    xmm1, xmm1, xmm1

LBB0_4:
	QUAD $0xfffffe20896f7ec5                   // vmovdqu    ymm9, yword [rcx - 480]
	QUAD $0xfffffe40916f7ec5                   // vmovdqu    ymm10, yword [rcx - 448]
	QUAD $0xfffffe60996f7ec5                   // vmovdqu    ymm11, yword [rcx - 416]
	QUAD $0xfffffe80a16f7ec5                   // vmovdqu    ymm12, yword [rcx - 384]
	LONG $0xefef35c5                           // vpxor    ymm13, ymm9, ymm7
	LONG $0xffdbb5c5                           // vpand    ymm7, ymm9, ymm7
	LONG $0xdb1541c4; BYTE $0xca               // vpand    ymm9, ymm13, ymm10
	LONG $0xffebb5c5                           // vpor    ymm7, ymm9, ymm7
	LONG $0xef1541c4; BYTE $0xca               // vpxor    ymm9, ymm13, ymm10
	LONG $0xef2541c4; BYTE $0xd1               // vpxor    ymm10, ymm11, ymm9
	LONG $0xdb2541c4; BYTE $0xc9               // vpand    ymm9, ymm11, ymm9
	LONG $0xdb2d41c4; BYTE $0xdc               // vpand    ymm11, ymm10, ymm12
	LONG $0xeb2541c4; BYTE $0xc9               // vpor    ymm9, ymm11, ymm9
	LONG $0xef2d41c4; BYTE $0xd4               // vpxor    ymm10, ymm10, ymm12
	LONG $0xdfef3dc5                           // vpxor    ymm11, ymm8, ymm7
	LONG $0xffdbbdc5                           // vpand    ymm7, ymm8, ymm7
	LONG $0xdb3541c4; BYTE $0xc3               // vpand    ymm8, ymm9, ymm11
	LONG $0xffebbdc5                           // vpor    ymm7, ymm8, ymm7
	LONG $0xef3541c4; BYTE $0xc3               // vpxor    ymm8, ymm9, ymm11
	QUAD $0xfffffea0896f7ec5                   // vmovdqu    ymm9, yword [rcx - 352]
	QUAD $0xfffffec0996f7ec5                   // vmovdqu    ymm11, yword [rcx - 320]
	LONG $0xef3541c4; BYTE $0xe2               // vpxor    ymm12, ymm9, ymm10
	LONG $0xdb3541c4; BYTE $0xca               // vpand    ymm9, ymm9, ymm10
	LONG $0xdb1d41c4; BYTE $0xd3               // vpand    ymm10, ymm12, ymm11
	LONG $0xeb2d41c4; BYTE $0xc9               // vpor    ymm9, ymm10, ymm9
	LONG $0xef1d41c4; BYTE $0xd3               // vpxor    ymm10, ymm12, ymm11
	QUAD $0xfffffee0996f7ec5                   // vmovdqu    ymm11, yword [rcx - 288]
	QUAD $0xffffff00a16f7ec5                   // vmovdqu    ymm12, yword [rcx - 256]
	LONG $0xef2541c4; BYTE $0xea               // vpxor    ymm13, ymm11, ymm10
	LONG $0xdb2541c4; BYTE $0xd2               // vpand    ymm10, ymm11, ymm10
	LONG $0xdb1541c4; BYTE $0xdc               // vpand    ymm11, ymm13, ymm12
	LONG $0xeb2541c4; BYTE $0xd2               // vpor    ymm10, ymm11, ymm10
	LONG $0xef1541c4; BYTE $0xdc               // vpxor    ymm11, ymm13, ymm12
	LONG $0xef3541c4; BYTE $0xe0               // vpxor    ymm12, ymm9, ymm8
	LONG $0xdb3541c4; BYTE $0xc0               // vpand    ymm8, ymm9, ymm8
	LONG $0xdb2d41c4; BYTE $0xcc               // vpand    ymm9, ymm10, ymm12
	LONG $0xeb3541c4; BYTE $0xc0               // vpor    ymm8, ymm9, ymm8
	LONG $0xef2d41c4; BYTE $0xd4               // vpxor    ymm10, ymm10, ymm12
	LONG $0xe6ef45c5                           // vpxor    ymm12, ymm7, ymm6
	LONG $0xf6dbc5c5                           // vpand    ymm6, ymm7, ymm6
	LONG $0xdb3dc1c4; BYTE $0xfc               // vpand    ymm7, ymm8, ymm12
	LONG $0xceeb45c5                           // vpor    ymm9, ymm7, ymm6
	LONG $0xef3dc1c4; BYTE $0xf4               // vpxor    ymm6, ymm8, ymm12
	QUAD $0xffffff20b96ffec5                   // vmovdqu    ymm7, yword [rcx - 224]
	QUAD $0xffffff40816f7ec5                   // vmovdqu    ymm8, yword [rcx - 192]
	LONG $0xe7ef25c5                           // vpxor    ymm12, ymm11, ymm7
	LONG $0xffdba5c5                           // vpand    ymm7, ymm11, ymm7
	LONG $0xdb1d41c4; BYTE $0xd8               // vpand    ymm11, ymm12, ymm8
	LONG $0xffeba5c5                           // vpor    ymm7, ymm11, ymm7
	LONG $0xef1d41c4; BYTE $0xc0               // vpxor    ymm8, ymm12, ymm8
	QUAD $0xffffff60996f7ec5                   // vmovdqu    ymm11, yword [rcx - 160]
	LONG $0x616f7ec5; BYTE $0x80               // vmovdqu    ymm12, yword [rcx - 128]
	LONG $0xef2541c4; BYTE $0xe8               // vpxor    ymm13, ymm11, ymm8
	LONG $0xdb2541c4; BYTE $0xc0               // vpand    ymm8, ymm11, ymm8
	LONG $0xdb1541c4; BYTE $0xdc               // vpand    ymm11, ymm13, ymm12
	LONG $0xeb2541c4; BYTE $0xc0               // vpor    ymm8, ymm11, ymm8
	LONG $0xef1541c4; BYTE $0xdc               // vpxor    ymm11, ymm13, ymm12
	LONG $0xe7ef2dc5                           // vpxor    ymm12, ymm10, ymm7
	LONG $0xffdbadc5                           // vpand    ymm7, ymm10, ymm7
	LONG $0xdb3d41c4; BYTE $0xd4               // vpand    ymm10, ymm8, ymm12
	LONG $0xd7eb2dc5                           // vpor    ymm10, ymm10, ymm7
	LONG $0xef3d41c4; BYTE $0xc4               // vpxor    ymm8, ymm8, ymm12
	LONG $0x796ffec5; BYTE $0xa0               // vmovdqu    ymm7, yword [rcx - 96]
	LONG $0x616f7ec5; BYTE $0xc0               // vmovdqu    ymm12, yword [rcx - 64]
	LONG $0xefef25c5                           // vpxor    ymm13, ymm11, ymm7
	LONG $0xffdba5c5                           // vpand    ymm7, ymm11, ymm7
	LONG $0xdb1541c4; BYTE $0xdc               // vpand    ymm11, ymm13, ymm12
	LONG $0xdfeb25c5                           // vpor    ymm11, ymm11, ymm7
	LONG $0xef15c1c4; BYTE $0xfc               // vpxor    ymm7, ymm13, ymm12
	LONG $0x616f7ec5; BYTE $0xe0               // vmovdqu    ymm12, yword [rcx - 32]
	LONG $0x296f7ec5                           // vmovdqu    ymm13, yword [rcx]
	LONG $0xf7ef1dc5                           // vpxor    ymm14, ymm12, ymm7
	LONG $0xffdb9dc5                           // vpand    ymm7, ymm12, ymm7
	LONG $0xdb0d41c4; BYTE $0xe5               // vpand    ymm12, ymm14, ymm13
	LONG $0xe7eb1dc5                           // vpor    ymm12, ymm12, ymm7
	LONG $0xef0dc1c4; BYTE $0xfd               // vpxor    ymm7, ymm14, ymm13
	LONG $0xef2541c4; BYTE $0xe8               // vpxor    ymm13, ymm11, ymm8
	LONG $0xdb2541c4; BYTE $0xc0               // vpand    ymm8, ymm11, ymm8
	LONG $0xdb1d41c4; BYTE $0xdd               // vpand    ymm11, ymm12, ymm13
	LONG $0xeb2541c4; BYTE $0xd8               // vpor    ymm11, ymm11, ymm8
	LONG $0xef1d41c4; BYTE $0xc5               // vpxor    ymm8, ymm12, ymm13
	LONG $0xe6ef2dc5                           // vpxor    ymm12, ymm10, ymm6
	LONG $0xf6dbadc5                           // vpand    ymm6, ymm10, ymm6
	LONG $0xdb2541c4; BYTE $0xd4               // vpand    ymm10, ymm11, ymm12
	LONG $0xd6eb2dc5                           // vpor    ymm10, ymm10, ymm6
	LONG $0xef25c1c4; BYTE $0xf4               // vpxor    ymm6, ymm11, ymm12
	LONG $0xd9ef35c5                           // vpxor    ymm11, ymm9, ymm1
	LONG $0xc9dbb5c5                           // vpand    ymm1, ymm9, ymm1
	LONG $0xdb2d41c4; BYTE $0xcb               // vpand    ymm9, ymm10, ymm11
	LONG $0xc9eb35c5                           // vpor    ymm9, ymm9, ymm1
	LONG $0xef2dc1c4; BYTE $0xcb               // vpxor    ymm1, ymm10, ymm11
	LONG $0x722dc1c4; WORD $0x04d1             // vpsrld    ymm10, ymm9, 4
	LONG $0xcbdb35c5                           // vpand    ymm9, ymm9, ymm3
	LONG $0x005d42c4; BYTE $0xc9               // vpshufb    ymm9, ymm4, ymm9
	LONG $0xd3db2dc5                           // vpand    ymm10, ymm10, ymm3
	LONG $0x005d42c4; BYTE $0xd2               // vpshufb    ymm10, ymm4, ymm10
	LONG $0xfc2d41c4; BYTE $0xc9               // vpaddb    ymm9, ymm10, ymm9
	LONG $0xcaf635c5                           // vpsadbw    ymm9, ymm9, ymm2
	LONG $0xedd4b5c5                           // vpaddq    ymm5, ymm9, ymm5
	LONG $0x10c08348                           // add    rax, 16
	LONG $0x00c18148; WORD $0x0002; BYTE $0x00 // add    rcx, 512
	WORD $0x394c; BYTE $0xc0                   // cmp    rax, r8
	JB   LBB0_4
	LONG $0xf573edc5; BYTE $0x04               // vpsllq    ymm2, ymm5, 4

LBB0_6:
	LONG $0xd172e5c5; BYTE $0x04   // vpsrld    ymm3, ymm1, 4
	LONG $0x656ffdc5; BYTE $0x00   // vmovdqa    ymm4, yword 0[rbp] /* [rip + LCPI0_0] */
	LONG $0xccdbf5c5               // vpand    ymm1, ymm1, ymm4
	LONG $0x6d6ffdc5; BYTE $0x20   // vmovdqa    ymm5, yword 32[rbp] /* [rip + LCPI0_1] */
	LONG $0x0055e2c4; BYTE $0xc9   // vpshufb    ymm1, ymm5, ymm1
	LONG $0xdcdbe5c5               // vpand    ymm3, ymm3, ymm4
	LONG $0x0055e2c4; BYTE $0xdb   // vpshufb    ymm3, ymm5, ymm3
	LONG $0xc9fce5c5               // vpaddb    ymm1, ymm3, ymm1
	LONG $0xc8f6f5c5               // vpsadbw    ymm1, ymm1, ymm0
	LONG $0xf173f5c5; BYTE $0x03   // vpsllq    ymm1, ymm1, 3
	LONG $0xcad4f5c5               // vpaddq    ymm1, ymm1, ymm2
	LONG $0xd672edc5; BYTE $0x04   // vpsrld    ymm2, ymm6, 4
	LONG $0xdcdbcdc5               // vpand    ymm3, ymm6, ymm4
	LONG $0x0055e2c4; BYTE $0xdb   // vpshufb    ymm3, ymm5, ymm3
	LONG $0xd4dbedc5               // vpand    ymm2, ymm2, ymm4
	LONG $0x0055e2c4; BYTE $0xd2   // vpshufb    ymm2, ymm5, ymm2
	LONG $0xd3fcedc5               // vpaddb    ymm2, ymm2, ymm3
	LONG $0xd0f6edc5               // vpsadbw    ymm2, ymm2, ymm0
	LONG $0xf273edc5; BYTE $0x02   // vpsllq    ymm2, ymm2, 2
	LONG $0x7265c1c4; WORD $0x04d0 // vpsrld    ymm3, ymm8, 4
	LONG $0xf4dbbdc5               // vpand    ymm6, ymm8, ymm4
	LONG $0x0055e2c4; BYTE $0xf6   // vpshufb    ymm6, ymm5, ymm6
	LONG $0xdcdbe5c5               // vpand    ymm3, ymm3, ymm4
	LONG $0x0055e2c4; BYTE $0xdb   // vpshufb    ymm3, ymm5, ymm3
	LONG $0xdefce5c5               // vpaddb    ymm3, ymm3, ymm6
	LONG $0xd8f6e5c5               // vpsadbw    ymm3, ymm3, ymm0
	LONG $0xdbd4e5c5               // vpaddq    ymm3, ymm3, ymm3
	LONG $0xd3d4edc5               // vpaddq    ymm2, ymm2, ymm3
	LONG $0xcad4f5c5               // vpaddq    ymm1, ymm1, ymm2
	LONG $0xd772edc5; BYTE $0x04   // vpsrld    ymm2, ymm7, 4
	LONG $0xdcdbc5c5               // vpand    ymm3, ymm7, ymm4
	LONG $0x0055e2c4; BYTE $0xdb   // vpshufb    ymm3, ymm5, ymm3
	LONG $0xd4dbedc5               // vpand    ymm2, ymm2, ymm4
	LONG $0x0055e2c4; BYTE $0xd2   // vpshufb    ymm2, ymm5, ymm2
	LONG $0xd3fcedc5               // vpaddb    ymm2, ymm2, ymm3
	LONG $0xc0f6edc5               // vpsadbw    ymm0, ymm2, ymm0
	LONG $0xc0d4f5c5               // vpaddq    ymm0, ymm1, ymm0
	LONG $0x397de3c4; WORD $0x01c1 // vextracti128    xmm1, ymm0, 1
	LONG $0xc1d4f9c5               // vpaddq    xmm0, xmm0, xmm1
	LONG $0xc870f9c5; BYTE $0xee   // vpshufd    xmm1, xmm0, 238
	LONG $0xc1d4f9c5               // vpaddq    xmm0, xmm0, xmm1
	LONG $0x7ef9c1c4; BYTE $0xc2   // vmovq    r10, xmm0
	LONG $0x02d6f9c5               // vmovq    qword [rdx], xmm0
	WORD $0x8941; BYTE $0xf0       // mov    r8d, esi
	LONG $0xc0e08341               // and    r8d, -64

LBB0_7:
	WORD $0x3941; BYTE $0xf0 // cmp    r8d, esi
	JAE  LBB0_12
	WORD $0x6349; BYTE $0xc8 // movsxd    rcx, r8d
	WORD $0xf741; BYTE $0xd0 // not    r8d
	WORD $0x0141; BYTE $0xf0 // add    r8d, esi
	WORD $0x8941; BYTE $0xf1 // mov    r9d, esi
	LONG $0x03e18341         // and    r9d, 3
	JE   LBB0_10

LBB0_9:
	LONG $0xb80f48f3; WORD $0xcf04 // popcnt    rax, qword [rdi + 8*rcx]
	WORD $0x0149; BYTE $0xc2       // add    r10, rax
	WORD $0x894c; BYTE $0x12       // mov    qword [rdx], r10
	LONG $0x01c18348               // add    rcx, 1
	LONG $0xffc18341               // add    r9d, -1
	JNE  LBB0_9

LBB0_10:
	LONG $0x03f88341 // cmp    r8d, 3
	JB   LBB0_12

LBB0_11:
	LONG $0xb80f48f3; WORD $0xcf04             // popcnt    rax, qword [rdi + 8*rcx]
	WORD $0x014c; BYTE $0xd0                   // add    rax, r10
	WORD $0x8948; BYTE $0x02                   // mov    qword [rdx], rax
	LONG $0xb80f4cf3; WORD $0xcf44; BYTE $0x08 // popcnt    r8, qword [rdi + 8*rcx + 8]
	WORD $0x0149; BYTE $0xc0                   // add    r8, rax
	WORD $0x894c; BYTE $0x02                   // mov    qword [rdx], r8
	LONG $0xb80f48f3; WORD $0xcf44; BYTE $0x10 // popcnt    rax, qword [rdi + 8*rcx + 16]
	WORD $0x014c; BYTE $0xc0                   // add    rax, r8
	WORD $0x8948; BYTE $0x02                   // mov    qword [rdx], rax
	LONG $0xb80f4cf3; WORD $0xcf54; BYTE $0x18 // popcnt    r10, qword [rdi + 8*rcx + 24]
	WORD $0x0149; BYTE $0xc2                   // add    r10, rax
	WORD $0x894c; BYTE $0x12                   // mov    qword [rdx], r10
	LONG $0x04c18348                           // add    rcx, 4
	WORD $0xf139                               // cmp    ecx, esi
	JB   LBB0_11

LBB0_12:
	VZEROUPPER
	RET
